# Generated by Django 6.0 on 2025-12-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultitem',
            old_name='uploaded_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='vaultitem',
            old_name='encrypted_data',
            new_name='secret_data',
        ),
    ]
