# Generated by Django 6.0 on 2025-12-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_rename_uploaded_file_vaultitem_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultitem',
            old_name='secret_data',
            new_name='encrypted_data',
        ),
        migrations.RenameField(
            model_name='vaultitem',
            old_name='file',
            new_name='uploaded_file',
        ),
    ]
